version: '3.7'
services:
  nginx:
      image: 'arm64v8/nginx:stable-alpine'
      container_name: api_gateway_nginx
      ports:
        - '8080:80'
      volumes:
        - ./:/var/www/html
        - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
      networks:
        - api_gateway_network
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: api_gateway_app
    volumes:
      - ./:/var/www/html
    networks:
      - api_gateway_network

#Volumes
volumes:
  dbdata:

networks:
  api_gateway_network:
    driver: bridge
